branches:
  only:
    - master
    - stable
install:
    - ps: Install-Product node 6.9.1 x64
    - npm install -g npm -s
    - npm install -g yarn -s
    - yarn install --force

build_script:
    - scripts/install/install-windows.bat

test_script:
    # - npm run test -s
